version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 22
  prebuild:
    command:
      - echo Logging into AWS ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password=stdin 282865065290.dkr.ecr.us-east-1.amazonaws.com/cursonodejs22
  build:
    commands:
      - echo Build started at `date`
      - echo Building the docker image
      - aws s3 cp s3://cursonodejs21/$ENVIRONMENT/.env .env
      - docker build -t cursonodejs21 .
      - docker tag cursonodejs21 282865065290.dkr.ecr.us-east-1.amazonaws.com/cursonodejs22
  post_build:
    commands:
      - docker push 282865065290.dkr.ecr.us-east-1.amazonaws.com/cursonodejs22
artifacts:
  files:
    - "Dockerrun.aws.json"
  
