### Get all users
get http://localhost:3000/user

### Get by User ID
get http://localhost:3000/user/2

### Get by page
get http://localhost:3000/user/page?page=1&limit=3


### Create a new user
post http://localhost:3000/user
Content-Type: application/json

{
  "name": "Juan",
  "lastname": "Carlos",
  "email": "juan.carlos@email.com",
  "password": "12345",
  "roles": [
    {"roleId": 1}, {"roleId": 2}
  ]
}

### Create a new user
put http://localhost:3000/user/2
Content-Type: application/json

{
  "name": "Juan"
}

### Delete by User ID
delete http://localhost:3000/user/2

### Delete cache
get http://localhost:3000/invalidate-cache
